# Generated by Django 3.2 on 2021-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymembers',
            name='dateOfBirth',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
